<div class="row-fluid">
    <div class="span12 page-header">
        <h1>
            <small class="text-info">Upload <?= $title ?></small>
            <a class="btn btn-info pull-right no-cover" href="<?= $template_link ?>"><i class="icon-download-alt icon-white"></i> Download Template</a>
        </h1>
    </div>
</div><div class="row-fluid">
    <div class="span6 offset3">
        <?= TwbForm::horizontal($form) ?>
    </div>
</div>