<div class="row-fluid">
    <div class="span12 page-header">
        <h1 class="text-important text-center">
			<button type="button" class="btn btn-inverse pull-left" onclick="history.back();"><i class="icon-white icon-chevron-left"></i> Back</button>
            Uploaded Data [<span class="text-error"><?= $title ?></span>]
			<?php if (!$form): ?>
				<a href="<?=
				$this->url($this->module(), $this->controller(), 'save-imports')
				?>" class="btn btn-success btn-large">
					<i class="icon-hdd icon-white"></i> Save
				</a>
			<?php endif; ?>
        </h1>
    </div>
</div>
<?php if ($form): ?>
	<div class="row-fluid">
		<div class="span12 page-header" style="margin-top:-20px;padding-bottom:0">
			<?= TwbForm::inline($form->setAttribute('action', $this->url($this->module(), $this->controller(), 'save-imports'))); ?>
		</div>
	</div>
<?php endif;
?>
<div class="row-fluid">
    <div class="span12">
		<?php
		Table::init(array('class' => 'table table-striped table-hover'));
		Table::setHeaders($imported[0]);
		Table::setFooters($imported[0]);
		unset($imported[0]);
		foreach ($imported as $imp) {
			Table::newRow();
			foreach ($imp as $i) {
				Table::addRowData($i);
			}
		}
		echo Table::render();
		?>
    </div>
</div>
